version: '3.3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'sale'
      MYSQL_USER: 'sale'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'